### ISSUE TITLE
FileNotFoundException: C:\GitHub\dsyme\FsLab\src\fsx2html/../styles/style.css

### ISSUE THREAD

**Issue by nakeep** [fslaborg/FsLab#143] opened 2018-09-18 06:03 UTC
When building HTML target for FSLab templates ,build fails on Windows 7 SP1 and on macOS Sierra with this exception:

Unhandled Exception:
System.IO.FileNotFoundException: C:\GitHub\dsyme\FsLab\src\fsx2html/../styles/style.css does not exist
File name: 'C:\GitHub\dsyme\FsLab\src\fsx2html/../styles/style.css'
  at System.IO.File.Copy (System.String sourceFileName, System.String destFileName, System.Boolean overwrite) [0x000b6] in <bb7b695b8c6246b3ac1646577aea7650>:0 
  at FSharp.Literate.Scripts.ScriptProcessing.copyFiles (System.String source, System.String target) [0x0005f] in <5b679bd17e74a3f4a7450383d19b675b>:0 
  at FSharp.Literate.Scripts.ScriptProcessing.processScriptFiles (System.Boolean overwrite, FSharp.Literate.Scripts.ProcessingContext ctx) [0x00084] in <5b679bd17e74a3f4a7450383d19b675b>:0 
  at Tool.generateJournals (FSharp.Literate.Scripts.ProcessingContext ctx) [0x00000] in <5b679bd17e74a3f4a7450383d19b675b>:0 
  at Tool.generateHtml (FSharp.Literate.Scripts.ProcessingContext ctx) [0x0002a] in <5b679bd17e74a3f4a7450383d19b675b>:0 
  at Tool.main (System.String[] argv) [0x002bf] in <5b679bd17e74a3f4a7450383d19b675b>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.IO.FileNotFoundException: C:\GitHub\dsyme\FsLab\src\fsx2html/../styles/style.css does not exist
File name: 'C:\GitHub\dsyme\FsLab\src\fsx2html/../styles/style.css'
  at System.IO.File.Copy (System.String sourceFileName, System.String destFileName, System.Boolean overwrite) [0x000b6] in <bb7b695b8c6246b3ac1646577aea7650>:0 
  at FSharp.Literate.Scripts.ScriptProcessing.copyFiles (System.String source, System.String target) [0x0005f] in <5b679bd17e74a3f4a7450383d19b675b>:0 
  at FSharp.Literate.Scripts.ScriptProcessing.processScriptFiles (System.Boolean overwrite, FSharp.Literate.Scripts.ProcessingContext ctx) [0x00084] in <5b679bd17e74a3f4a7450383d19b675b>:0 
  at Tool.generateJournals (FSharp.Literate.Scripts.ProcessingContext ctx) [0x00000] in <5b679bd17e74a3f4a7450383d19b675b>:0 
  at Tool.generateHtml (FSharp.Literate.Scripts.ProcessingContext ctx) [0x0002a] in <5b679bd17e74a3f4a7450383d19b675b>:0 
  at Tool.main (System.String[] argv) [0x002bf] in <5b679bd17e74a3f4a7450383d19b675b>:0 
fsx2html.exe --html failed

**Comment by whatevergeek** [comment] 2018-09-20 10:51
same here... on Windows 10

`Unhandled Exception: System.Exception: couldn't find styles
   at FSharp.Literate.Scripts.ProcessingContext.Create(String root)
   at Tool.createContext(String source, String output)
   at Tool.main(String[] argv)`

**Comment by wuleicanada** [comment] 2018-10-01 18:08
It seems __SOURCE_DIRECTORY__ was hardcoded as "C:\GitHub\dsyme\FsLab\src\fsx2html" within \packages\FSharp.Literate.Scripts\tools\fsx2html.exe

I worked around it by creating a "C:\GitHub\dsyme\FsLab" folder and extracting the GitHub source there.

**Comment by whatevergeek** [comment] 2018-10-02 01:01
Hi @wuleicanada !
Thanks for sharing. I'll try this later.q

**Comment by whatevergeek** [comment] 2018-10-02 04:47
yap... creating a "C:\GitHub\dsyme\FsLab" works... this is just a work around though...

**Comment by whatevergeek** [comment] 2018-10-02 04:54
hi @dsyme @tpetricek , 
i was looking for a contributing document to get the fix done but didn't find...
is this project open to community contributions?

**Comment by dsyme** [comment] 2018-10-02 10:40
oops, my apologies for the mistake.

Yes, we absolutely accept contributions.

**Comment by dsyme** [comment] 2018-10-02 10:46
The problem is in these lines https://github.com/fslaborg/FsLab/blob/master/src/fsx2html/ScriptProcessing.fs#L43-L45

**Comment by dsyme** [comment] 2018-10-02 12:55
Fixed in 1.1.6 and in #144  https://github.com/fslaborg/FsLab/pull/144/files#diff-28f54be274974cf7b991efbf12a9aedeR43

**Comment by dsyme** [comment] 2018-10-02 12:55
Please try latest nugets

**Comment by whatevergeek** [comment] 2018-10-02 13:32
cool! thanks @dsyme

**Comment by dsyme** [comment] 2018-10-03 08:42
Great

**Closed** 2018-10-03 08:42 UTC

**Comment by nakeep** [comment] 2018-10-08 22:17
It works now.
